"""Add execution_log to turn

Revision ID: 3300355a0511
Revises: c00ab6368026
Create Date: 2024-12-16 07:16:38.067760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3300355a0511'
down_revision: Union[str, None] = 'c00ab6368026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('execution_log_id', sa.Integer(), nullable=False))
    op.alter_column('turns', 'nlq',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('turns_sqid_fkey', 'turns', type_='foreignkey')
    op.create_foreign_key(None, 'turns', 'execution_logs', ['execution_log_id'], ['id'])
    op.drop_column('turns', 'sqid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('sqid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'turns', type_='foreignkey')
    op.create_foreign_key('turns_sqid_fkey', 'turns', 'sql_queries', ['sqid'], ['sqid'])
    op.alter_column('turns', 'nlq',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('turns', 'execution_log_id')
    # ### end Alembic commands ###
