"""added saved_by column in saved_query table

Revision ID: 77ac5396e272
Revises: 0c7ee47b1be8
Create Date: 2024-12-14 19:51:01.093610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ac5396e272'
down_revision: Union[str, None] = '0c7ee47b1be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_queries', sa.Column('saved_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'saved_queries', 'users', ['saved_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_queries', type_='foreignkey')
    op.drop_column('saved_queries', 'saved_by')
    # ### end Alembic commands ###
