"""add database used

Revision ID: c00ab6368026
Revises: 118cb7106abf
Create Date: 2024-12-16 01:15:59.683122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00ab6368026'
down_revision: Union[str, None] = '118cb7106abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sql_queries', sa.Column('database_used', sa.String(), nullable=True))
    op.alter_column('sql_queries', 'sqlquery',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sql_queries', 'sqlquery',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('sql_queries', 'database_used')
    # ### end Alembic commands ###
